services:
  - type: web
    name: fitness-console
    env: python
    buildCommand: pip install -r requirements.txt && cd frontend && export NODE_VERSION=18 && npm ci && npm run build && cd .. && mkdir -p backend/static && cp -r frontend/build/* backend/static/
    startCommand: gunicorn backend.app:app
    healthCheckPath: /api/status
    envVars:
      - key: FLASK_DEBUG
        value: "False"
      - key: FLASK_SECRET_KEY
        sync: false
      - key: FITBIT_CLIENT_ID
        sync: false
      - key: FITBIT_CLIENT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: "https://fitness-console.onrender.com"
      - key: FITBIT_REDIRECT_URI
        value: "https://fitness-console.onrender.com/api/auth/callback"
      - key: APPLE_FITNESS_REDIRECT_URI
        value: "https://fitness-console.onrender.com/api/apple-fitness/callback"