services:
  - type: web
    name: fitness-console
    env: python
    buildCommand: >
      pip install -r requirements.txt && 
      cd frontend && 
      export NODE_VERSION=18 && 
      npm install --no-audit --no-fund && 
      CI=false npm run build && 
      cd .. && 
      rm -rf backend/static && 
      mkdir -p backend/static && 
      cp -r frontend/build/* backend/static/ &&
      ls -la backend/static
    startCommand: cd backend && gunicorn app:app --log-level debug --timeout 120
    healthCheckPath: /api/status
    envVars:
      - key: FLASK_DEBUG
        value: "False"
      - key: FLASK_SECRET_KEY
        sync: false
      - key: FITBIT_CLIENT_ID
        sync: false
      - key: FITBIT_CLIENT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: "https://fitness-console-gtxc.onrender.com"
      - key: FITBIT_REDIRECT_URI
        value: "https://fitness-console-gtxc.onrender.com/api/auth/callback"
      - key: APPLE_FITNESS_REDIRECT_URI
        value: "https://fitness-console-gtxc.onrender.com/api/apple-fitness/callback"